### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by SamVerschueren**

### CODE REVIEW

**Comment by SamVerschueren** [comment]
It looks like that XO version isnt werking on 0.10 anymore. Some dependency maybe?

**Comment by shinnn** [comment]
@SamVerschueren Probably https://github.com/npm/write-file-atomic/issues/18

**Comment by SamVerschueren** [comment]
Apparently they are fixing it but I'm closing this in favour of #3

**Comment by SamVerschueren** [comment]
Thanks for the link by the way @shinnn !

**Pull request closed without merging**
